apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: song-service-k8s
  template:
    metadata:
      labels:
        app: song-service-k8s
    spec:
      containers:
        - name: song-service-k8s
          image: brianmaymc/song-service:latest
          ports:
            - protocol: TCP
              containerPort: 8080
