apiVersion: v1
kind: Service
metadata:
  name: azure-workflow
  namespace: namespace-workflow-1716980627741
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: azure-workflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080