apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
      - name: song-service
        image: brianmaymc/song-service:latest
        ports:
          - protocol: TCP
            containerPort: 8080
        env:
          - name: SERVER_SERVLET_CONTEXT_PATH
            value: "/song"
          - name: MONGODB_URL
            value: mongodb://mongo:27017/
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: brianmaymc/user-service:latest
        ports:
          - protocol: TCP
            containerPort: 8081
        env:
          - name: SERVER_SERVLET_CONTEXT_PATH
            value: "/user"
          - name: MONGODB_URL
            value: mongodb://mongo:27017/
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-service
  template:
    metadata:
      labels:
        app: playlist-service
    spec:
      containers:
      - name: playlist-service
        image: brianmaymc/playlist-service:latest
        ports:
          - protocol: TCP
            containerPort: 8082
        env:
          - name: SERVER_SERVLET_CONTEXT_PATH
            value: "/playlist"
          - name: MONGODB_URL
            value: mongodb://mongo:27017/
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq