name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Push Docker images
      run: |
        docker build -t song-service ./song-service
        docker build -t playlist-service ./playlist-service
        docker build -t user-service ./user-service

        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

        docker tag song-service ${{ secrets.DOCKER_USERNAME }}/song-service:latest
        docker tag playlist-service ${{ secrets.DOCKER_USERNAME }}/playlist-service:latest
        docker tag user-service ${{ secrets.DOCKER_USERNAME }}/user-service:latest

        docker push ${{ secrets.DOCKER_USERNAME }}/song-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/playlist-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

    - name: Deploy to Kubernetes
      env:
        KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
        KUBE_CA_CERT: ${{ secrets.KUBE_CA_CERT }}
        KUBE_CLIENT_CERT: ${{ secrets.KUBE_CLIENT_CERT }}
        KUBE_CLIENT_KEY: ${{ secrets.KUBE_CLIENT_KEY }}
      run: |
        echo $KUBE_CA_CERT | base64 --decode > ca.crt
        echo $KUBE_CLIENT_CERT | base64 --decode > client.crt
        echo $KUBE_CLIENT_KEY | base64 --decode > client.key
        kubectl apply -f kubernetes/ --server=$KUBE_SERVER --certificate-authority=ca.crt --client-certificate=client.crt --client-key=client.key
